### ISSUE TITLE
Support for querying nested properties in Search Bar

### ISSUE THREAD

**Issue by jprabawa** [homeaway/kibana#11]
Specifying queries in the Search Bar (i.e. https://www.elastic.co/guide/en/kibana/4.5/discover.html#search) does not work on Nested Properties.

For example, if the index mapping is:
```
{
    "library": {
        "mappings": {
            "book": {
                "dynamic": "strict",
                "properties": {
                    "reviewer": {
                        "type": "nested",
                        "properties": {
                            "name": {
                                "type": "string",
                                "index": "analyzed",
                                "analyzer": "standard",
                                "fields": {
                                    "raw": {
                                        "type": "string",
                                        "index": "not_analyzed"
                                    }
                                }
                            },
                            "country": {
                                "type": "string"
                            },
                            "age": {
                                "type": "integer"
                            }
                        }
                    }
                }
            }
        }
    }
}
```

Specifying a query like the following in the Search Box returns no results:

```
reviewer.name.raw: "John Doe"
```

**Comment by ppadovani** [comment]
This is correct. The simplified query language used by Elasticsearch does not natively support nested queries, only the JSON does. In order to support nested queries, I ported a simple query language that provides most of the same features but is instead loosely based on SQL. The search box will detect which query language you are using automatically. The custom parser will convert the SQL like query into a native Elasticsearch JSON query that is properly formatted.

The above query should instead be written as:

reviewer.name.raw = "John Doe"

For a description of the syntax, please see the RADME: https://github.com/homeaway/kibana/blob/nestedSupport-4.5.4/NESTED_README.md

**Comment by jprabawa** [comment]
Ah! I missed the readme. Apologies and Thanks!
