### ISSUE TITLE
Upgrade Kibana to 5.6

### ISSUE THREAD

**Issue by xhao6** [homeaway/kibana#29]
Currently the ELK stack has been upgraded to version 5.6, with some amazing updates. Is there a plan that upgrading the nested support from 5.2 to 5.6?

BTW, thanks a lot for the work. The nested support has made a big difference.

**Comment by Hronom** [comment]
Also it includes this fix https://github.com/elastic/elasticsearch/pull/23493 for new kernels, wich is very important

**Comment by ppadovani** [comment]
Update: I have been working on this, but have nothing ready. The Kibana team completely rewrote how field mappings are fetched from Elasticsearch. It will take some additional time to fully understand what and how their code behaves in order to properly patch my code. 

Sorry folks, I was hoping for a quick and easy patch of the code from the 5.2 version. I may have to patch each major version of 5.X in order to make my life easier. I'll update again when I have a status update.

**Comment by ppadovani** [comment]
I've ported and pushed the nested support to 5.3 and 5.4 branches, but haven't tested it yet.

5.5 is where the major changes have been put in place. It looks like it was committed as part of the cross cluster search feature. I would anticipate possibly having something working on 5.5 within another week.

**Comment by ppadovani** [comment]
Ok, this will take longer than expected. I am thinking of taking a different approach for this release and beyond. The plugin system for Kibana has a 'hack' interface that might allow me to inject the nestedSupport code where it needs to show up. So I am going to prototype a plugin for Kibana that attempts to inject nested support code into the areas that may be the hardest to update. If I can get that working, then I'll go after building a full fledged plugin and not maintain a fork of Kibana.

**Comment by ppadovani** [comment]
I should be able to replicate all of the nested support into a Kibana plugin. I have created the following GitHub repo for the work: https://github.com/ppadovani/KibanaNestedSupportPlugin

I will hopefully have this done before the end of the year. See that repository for status updates. When that plugin is available I will close this ticket.

**Comment by ppadovani** [comment]
I have released a Beta of the above mentioned plugin, and will now close this issue.
